name: geoJson

on: push

jobs:
  geoJson:
    name: geoJson
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: make project
        run: make
      - name: Run test
        run: make test
      
